name: sono
description: "A fresh start for Sono"
publish_to: "none"

version: 0.10.1+11

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any

  sono_query:
    #path: ../sono_query
    git:
      url: https://github.com/appsono/sono_query.git
      ref: v0.8.4

  # audio stuff
  media_kit: ^1.2.6
  media_kit_libs_audio: ^1.0.7
  audio_service: ^0.18.18
  audio_service_mpris: ^0.2.1 #linux MPRIS2 media session
  smtc_windows: ^1.1.0 #windows system media transport controls

  # db stuff
  drift: ^2.32.0
  #reading old wtf.sono.app db
  sqlite3: ^3.1.7
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.5
  path: ^1.9.1
  audio_session: ^0.2.2
  rxdart: ^0.28.0

  # image stuff
  image_picker: ^1.2.3
  image_picker_android: ^0.8.13+17
  image_picker_platform_interface: ^2.11.1

  # other stuff
  flutter_dotenv: ^6.0.0
  flutter_inappwebview: ^6.1.5
  flutter_svg: ^2.2.4
  flutter_secure_storage: ^10.0.0
  permission_handler: ^12.0.1
  crypto: ^3.0.7
  http: ^1.6.0
  package_info_plus: ^9.0.1
  url_launcher: ^6.3.2
  material_color_utilities: ^0.13.0
  image: ^4.8.0
  file_picker: ^11.0.2
  share_plus: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  drift_dev: ^2.32.0
  build_runner: ^2.12.2
  test: ^1.30.0

dependency_overrides:
  flutter_rust_bridge: 2.11.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/app/icon/
    - assets/app/icons/outlined/
    - assets/app/icons/filled/
    - assets/app/brands/
    - assets/app/translators.json
    - CHANGELOG.md

  fonts:
    - family: VarelaRound
      fonts:
        - asset: assets/app/fonts/VarelaRound/VarelaRound-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/app/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/app/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/app/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/app/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
