name: sono
description: "A fresh start for Sono"
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  on_audio_query:
    git:
      # yes, I'm still using on_audio_query, because it's the best solution I've found
      # and because I've made my own version of it already.
      url: https://github.com/appsono/on_audio_query.git
      path: packages/on_audio_query
      ref: v3.0.5

  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/app/icon/
    - assets/app/icons/