name: Android Build
on: [push]

jobs:
  build-android:
    container: ghcr.io/cirruslabs/flutter:stable
    env:
      PUB_CACHE: /workspace/.pub-cache
    steps:
      - name: Dependencies
        run: flutter pub get

      - name: Translation progress
        run: dart run scripts/compute_translation_progress.dart

      - name: Build APKs
        run: flutter build apk --release --flavor prod

      - name: Build App Bundle
        run: flutter build appbundle --release --flavor prod
